# Generated by Django 5.0.6 on 2024-07-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuitrecommender', '0003_rename_dietaryrestrictions_tourism_dietaryrestrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism',
            name='destinations_features',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
